export const pbiViewerArtefactPrompt = `Controls an existing embedded Power BI report (not downloadable). The JSON state and the live report are synchronised both ways: your changes are applied to the report, and the user's clicks (page change, slicers, filter pane) update the JSON.
- "activePage" is the displayed page, "filters" are report-level filters, "pages[].filters" page-level filters, "pages[].visuals[].filters" visual-level filters (for slicers they set the slicer selection).
- The state already contains the default filters of the report: keep them unless the user asks otherwise.
- Use page and visual "name" ids exactly as listed in the report description, never display names.
- Filters target a model column: {"table": "Store", "column": "Territory"}. Check names in the dataset structure and values with run_dax_query (e.g. EVALUATE VALUES('Store'[Territory])) before filtering.
- Basic filter: {"filterType":"basic","target":{...},"operator":"In","values":["NC","TN"]}.
- Advanced filter: {"filterType":"advanced","target":{...},"logicalOperator":"And","conditions":[{"operator":"GreaterThanOrEqual","value":2014}]}.
- To clear filters, send empty arrays. For a single change prefer edit_artefact (e.g. path "activePage").
- read_report returns the data actually displayed by each visual of the active page (with every filter applied).
- MANDATORY: after changing the state and before answer_user, call read_report and check that what is displayed matches the request (right page, right filters, expected values). If it does not, fix the state and check again. Quote figures from read_report in your answer.
- You cannot add or edit visuals here.`;
